# configs of task
n_classes: 3
task: 'renal_subtype'

# configs of path
data_root_dir: '/home3/gzy/Renal/feature_resnet/'
data_sp_dir: '/home3/gzy/Renal/sp_n16_c50_2048/'
label_frac: 1.0
models_dir: None
# '/home1/gzy/Nature/SQMILS/results_lung/lung_subtyping_WSODNIC_dropv2_spg10_res50_1512_5fold_s1/'

results_dir: './results/'
exp_code: 'renal_subtyping_iamil_res50_1512_5fold'

# configs of training
seed: 1
k: 5
k_start: 0
k_end: 5
max_epochs: 200
lr: 0.00002
reg: 0.00001
early_stopping: True
drop_out: True
drop_rate: 0.25
opt: 'adam'
bag_loss: 'bce'
weighted_sample: True
log_data: True
testing: False

# configs of model
model_type: 'sqmil_nic'
model_size: 'big'
fea_dim: 1024
consistency: False
drop_with_score: False
superpixel: False
G: 10
inst_refinement: False
inst_rate: 0.1
n_refs: 1
ref_start_epoch: 0
mrf: False
tau: 1