# configs of task
n_classes: 3
task: 'gastric_subtype'
multi_label: True

# configs of path
data_root_dir: '/home3/gzy/Gastric/feature_resnet/'
data_sp_dir: '/home3/gzy/Gastric/sp_n9_c50_2048/'
label_frac: 1.0
models_dir: None
# '/home1/gzy/Nature/SQMILM/results_gastric/new_ablation/gastric_subtyping_sqmil_ml_biloss_drop_spg10_n9_s1/'

results_dir: './results/'
exp_code: 'gastric_subtyping_smmile_res50_1512_5fold'

# configs of training
seed: 1
k: 5
k_start: 0
k_end: 5
max_epochs: 200
lr: 0.00002
reg: 0.00001
early_stopping: True
drop_out: True
drop_rate: 0.25
opt: 'adam'
bag_loss: 'bibce' # bibce
weighted_sample: True
log_data: True
testing: False

# configs of model
model_type: 'smmile'
model_size: 'small'
fea_dim: 1024
consistency: True # attention consistency for negative bags
drop_with_score: True # instance drop out
superpixel: True # instance sampling
G: 10 # number of instance sampling times
inst_refinement: False # instance refinement
inst_rate: 0.1 # instance rate for pseudo label generation
n_refs: 3 # number of layers for the refinement network
ref_start_epoch: 0 # 0 for instance refinement
mrf: False # MRF constraint for instance refinement
tau: 0.1 # weight control for MRF constraint