# configs of task
n_classes: 2
task: 'lung_subtype'

# configs of path
data_root_dir: '/home/shared/su123/TCGA_Embed/conch/TCGA-LUNG/' # patch embedding path
data_sp_dir: '/home/z/zeyugao/dataset/WSIData/TCGA-LUNG/sp_conch_n16_c50_2048' # superpixel segmentation map path
label_frac: 0.8
models_dir: None # set model path for second round instance refinement training
data_mag: '1_512'
patch_size: 2048
fea_dim: 512

results_dir: './results_conch_lung/'
exp_code: 'lung_subtyping_smmile_1512_5fold'

# configs of training
reverse_train_val: False # 20 train 80 val
seed: 1
k: 5
k_start: 0
k_end: 5
max_epochs: 50
lr: 0.00002
reg: 0.00001
early_stopping: True
drop_out: True
drop_rate: 0.25
opt: 'adam'
bag_loss: 'bce'
weighted_sample: True
log_data: True
testing: False

# configs of model
model_type: 'smmile'
model_size: 'small'
consistency: False # attention consistency for negative bags
drop_with_score: False # instance drop out
D: 10 # drop out times
superpixel: False # instance sampling
G: 10 # number of instance sampling times
sp_smooth: True
inst_refinement: False # instance refinement
inst_rate: 0.1 # instance rate for pseudo label generation
n_refs: 3 # number of layers for the refinement network
ref_start_epoch: 0 # 0 for instance refinement
mrf: False # MRF constraint for instance refinement
tau: 0.1 # weight control for MRF constraint

# python eval.py --data_root_dir /home/shared/su123/TCGA_Embed/conch/TCGA-LUNG/ --data_sp_dir /home/z/zeyugao/dataset/WSIData/TCGA-LUNG/sp_conch_n16_c50_2048 \
# --results_dir ./results_conch_lung_20/ --models_exp_code smmile_sp_ref_mrf_s1 --split train