# configs of task
n_classes: 5
task: 'ovarian_subtype'

# configs of path
data_root_dir: '/home/z/zeyugao/dataset/WSIData/UBC-OCEAN/clam_gen/resnet50/' # patch embedding path
data_sp_dir: '/home/z/zeyugao/dataset/WSIData/UBC-OCEAN/clam_gen/sp_n16_c50_512/' # superpixel segmentation map path
label_frac: 1.0
models_dir: None # set model path for second round instance refinement training
data_mag: '0_512'
patch_size: 512
fea_dim: 1024

results_dir: './results_clres_ov/'
exp_code: 'ov_subtyping_smmile_0512_5fold'

# configs of training
seed: 1
k: 5
k_start: 0
k_end: 5
max_epochs: 100
lr: 0.00002
reg: 0.00001
early_stopping: True
drop_out: True
drop_rate: 0.25
opt: 'adam'
bag_loss: 'bce'
weighted_sample: True
log_data: True
testing: False

# configs of model
model_type: 'smmile'
model_size: 'small'
consistency: False # attention consistency for negative bags
drop_with_score: False # instance drop out
D: 10 # drop out times
superpixel: False # instance sampling
sp_smooth: True
G: 10 # number of instance sampling times
inst_refinement: False # instance refinement
inst_rate: 0.1 # instance rate for pseudo label generation
n_refs: 3 # number of layers for the refinement network
ref_start_epoch: 0 # 0 for instance refinement
mrf: False # MRF constraint for instance refinement
tau: 0.1 # weight control for MRF constraint